import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/component/Nav";
import 'server-only'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Nav /> */}
        {children}
      </body>
    </html>
  );
}

// export async function getServerSideProps() {
//   const res = await fetch("https://raw.githubusercontent.com/dariusk/corpora/master/data/plants/flowers.json?limit=10");
//   const data = await res.json();

//   console.log("data json:",data)

//   return {
//     props: {
//       posts: data,
//     },
//   };
// }

